# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_articledetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name_plural': '备注_文章'},
        ),
        migrations.RemoveField(
            model_name='articledetail',
            name='nid',
        ),
        migrations.AddField(
            model_name='articledetail',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
