# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170525_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sn',
            field=models.CharField(default=1, max_length=128, unique=True, verbose_name='资产SN号'),
            preserve_default=False,
        ),
    ]
