# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-22 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20170622_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ram',
            name='asset',
        ),
        migrations.AddField(
            model_name='memory',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Asset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memory',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='memory',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='capacity',
            field=models.IntegerField(default=1, verbose_name='内存大小(MB)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memory',
            name='model',
            field=models.CharField(max_length=128, verbose_name='内存型号'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='slot',
            field=models.CharField(max_length=64, verbose_name='插槽'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SN号'),
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
    ]
