# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-22 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20170622_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name': '内存', 'verbose_name_plural': '内存表'},
        ),
        migrations.RemoveField(
            model_name='memory',
            name='server_obj',
        ),
    ]
